### ISSUE TITLE
Aquivo final compactado está com toda estrutura de subpastas

### ISSUE THREAD

**Issue by henriquejaspi** [henriqueholtz/Holtz_Compactador#2]
Aquivo final compactado está com toda estrutura de subpastas, por exemplo os arquivos estão em "C:\PastaX\PastaY\PastaZ\"
O arquivo zipado vai ter toda essa estrutura de pastas, "PastaX\PastaY\PastaZ\" para depois chegar nos arquivos zipados.

**Comment by henriqueholtz** [comment]
Problema corrigido! Commit da correção: 333c898034853feef49e01e97ac2e843b1ea7b84
